version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: sudo yarn global add semantic-release
      - run: yarn install
      - run: yarn test
      - run: semantic-release
